name: Container Build & Push

on:
  push:
    branches:
      - "main"
    paths:
      - "Containerfile"

jobs:
  docker-hub:
    name: Container Build and Push
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:latest
